[package]
name = "breakpoint-client"
description = "WASM browser client for Breakpoint"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
breakpoint-core = { path = "../breakpoint-core" }
serde.workspace = true
serde_json.workspace = true
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["console"] }

[lints]
workspace = true
